wit: add resources
bytecodealliance/component-docs pull request #103
Opened 2024-03-13 19:29 UTC by kate-goldenring

Mainly copied over from: https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md#item-resource

Also added a handles subsection

closes #97

2024-03-13 20:38 UTC, itowlson requested changes
This is great - thank you so much for wading into a difficult and nuanced topic.  I'm afraid I had a few areas where I got confused, some of which is down to the design and we probably need to punt on those for this PR and iterate on them over time, but some of which can hopefully addressed by some reorganising.  But this is an area where every concept seems to depend on every other concept, so I may be being optimistic... if it gets problematic then I'm totally up for landing this as is and continuing to noodle on it as the community learns what sort of explanations work best.

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +    merge: static func(lhs: borrow<blob>, rhs: borrow<blob>) -> blob;
Maybe add a comment reassuring the reader not to worry about `borrow` for now and it will be explained below?

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed self parameter whereas constructors always
I found this paragraph hard to parse - it felt like I'd suddenly been dropped into a Rust compiler implementors' chat.  What is borrowing?  Do I need to care about desugaring?  What do you want me as a _user_ of resources, as opposed to someone implementing them in a Wasm runtime, to understand here?

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +[above](#resources) desugars to:
Might want some more subheadings or anchors if we want to do links _within_ this section?

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +%[constructor]blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
Under what circumstances do application developers need to know about the mangled forms?  If we have a "how resources work" section then this would be great to have there but I'd keep it out of the WIT guide.

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +A flag type is a set of named booleans.  In an instance of the type, each flag will be either true or false.
`flags` here was intentional because the type expresses a _set_ of flags not a single flag.

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +There are two types of handles in Wit: "owned" handles and "borrowed" handles.
```suggestion
There are two types of handles in WIT: "owned" handles and "borrowed" handles.
```

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +There are two types of handles in Wit: "owned" handles and "borrowed" handles.
Oh, okay, so resources _only ever_ surface as handles!  I think it would be good to explain that closer to where resources and handles are introduced, maybe with some suitable analogy.

(also the earlier text said handles represent ownership so having this additional "may represent ownership or borrowed reference" up there would help set the reader on the right track)

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +handle that will *not* call the destructor when dropped.
Oof, I can see a lot of readers finding this tricky - not because of what you've written, but because the design is so predicated on Rust-like notions of ownership and borrowing.  "So is a borrow like a pointer?  Yes, but owning is like a pointer too..."  I don't have any good ideas for explaining it, though!  But let's get this in and we can keep iterating on it!

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +"owning" handle that will call the resource's destructor when dropped. When a
This somewhat recapitulates the distinction described in the previous paragraph.  Maybe merge the two paragraphs, possibly as a bullet of "owned means ... and has X characteristics / borrowed means ... and has Y characteristics"?

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +two components. When the owner of an owned handle drops that handle, the
`drop` is Rustspeak.  Can we translate / analogise it?  Should we break out a section on resource lifetimes / lifecycles?

(or maybe that is a matter for future iteration)

2024-03-13 20:38 UTC, itowlson commented on component-model/src/design/wit.md
> +A resource type defines a new abstract type an entity with a lifetime. Unlike
Another important characteristic of an entity/resource is identity.  If I hand over a `Point` record to a callee, the copy in the callee is a different record and can be manipulated separately.  If I hand over a `Car` resource, the callee is using _my_ `Car` - there's only one actual `Car`.  Like if the borrower drives its reference into a lamp post, my windscreen gets broken.

2024-03-13 21:01 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed self parameter whereas constructors always
I almost did add a section on handles. Should i simplify all of this and remove any deep dive into handles?

2024-03-13 21:06 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +handle that will *not* call the destructor when dropped.
Most of this I directly pulled over from WIT.md, which is likely a more technical audience. We could pull some of this out

2024-03-13 21:12 UTC, itowlson commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed self parameter whereas constructors always
It seems like there needs to be something about borrowed vs owned, but yeah, it's worth seeing if just calling things "resources" would work.  (Although it might be good to say "the spec distinguishes between resources and handles, but that's a runtime implementation concern," in case someone reads the spec and is wondering why it talks about things differently.)

Re the broader question, to me this is meant to be a "what you need to know to write WITs for your components (or read WITs for somebody else's components" (and I haven't looked at it since the initial writing frenzy so it may not be well aligned to that vision).  That reflects the idea of the book as being for readers trying to _get stuff done_ with the component model, rather than a re-layout or curation of the design docs.  But that's definitely a question that should be addressed by the wider SIG - I'm only one voice for sure!

2024-03-13 21:26 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed self parameter whereas constructors always
I think I am aligned with the idea of provide enough information to get stuff done. And this doc is about syntactical keywords, which `handle` is not one of. I removed most references to `handle` and simplified the section. Do you mind reviewing it again?

2024-03-13 21:28 UTC, itowlson commented on component-model/src/design/wit.md
> +    - [Resources](#resources)
Hiccup: Flags has disappeared from TOC

2024-03-13 21:31 UTC, itowlson commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed self parameter whereas constructors always
I like it!  I don't think anything significant to app developers is lost in the simplification (though I may turn out to be wrong), and I definitely felt more comfortable with the concepts this time around.  Thank you!

2024-03-13 21:33 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +%[constructor]blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
Good point. I updated this to say "it could also be written as" and expanded the function signatures. I will say i am not positive this expansion of methods is syntactically correct. @lann @dicej, are these equivalent?:

```wit
resource blob {
    constructor(init: list<u8>);
    write: func(bytes: list<u8>);
    read: func(n: u32) -> list<u8>;
    merge: static func(lhs: borrow<blob>, rhs: borrow<blob>) -> blob;
}
 // Verses
resource blob {
    blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
    write: func(self: borrow<blob>, bytes: list<u8>);
    read: func(self: borrow<blob>, n: u32) -> list<u8>;
    merge: static func(lhs: borrow<blob>, rhs: borrow<blob>) -> blob;
}
```

I am trying to illustrate how it is desugared to the following without showing that level of complexity:
```wit
resource blob;
%[constructor]blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
%[method]blob.write: func(self: borrow<blob>, bytes: list<u8>);
%[method]blob.read: func(self: borrow<blob>, n: u32) -> list<u8>;
%[static]blob.merge: func(lhs: borrow<blob>, rhs: borrow<blob>) -> blob;
```

2024-03-13 21:36 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +    - [Resources](#resources)
Thanks! Fixed

2024-03-13 22:11 UTC, lann commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
Might want to add a callout here with a little more information, maybe something along the lines of:

> Unlike all other WIT types, a resource type is unique to the instance that defines it. Two resource types with the same name defined in different components - even two instances of the same component - are distinct types.

2024-03-13 22:18 UTC, lann commented on component-model/src/design/wit.md
> +always desugar to an owned return value. For example, the `blob` constructor
```suggestion
always desugar to an owned return value. For example, the `blob` resource
```

2024-03-13 22:20 UTC, itowlson commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
Is there a way to characterise that in terms of component developer implications because I opened that link and now my brain is hiding under the sofa

2024-03-13 22:22 UTC, lann commented on component-model/src/design/wit.md
> +[above](#resources) could also be written as:
I think this could be interpreted as saying that the two definitions are _identical_ which would be misleading.

Hard to get the language exactly right here without being too wordy or formal, but maybe something like:

```suggestion
[above](#resources) could be approximated as:
```

2024-03-13 22:26 UTC, lann commented on component-model/src/design/wit.md
> +}
I know this has seen a few iterations already so feel free to ignore; it might still be worth splitting these out into separate functions _without_ getting into name mangling:

```suggestion
resource blob;
blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
write: func(self: borrow<blob>, bytes: list<u8>);
read: func(self: borrow<blob>, n: u32) -> list<u8>;
merge: static func(lhs: borrow<blob>, rhs: borrow<blob>) -> blob;

```

2024-03-13 22:26 UTC, lann commented on component-model/src/design/wit.md
> +    blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
```suggestion
    blob: func(bytes: list<u8>) -> blob;
```

2024-03-13 22:28 UTC, lann commented on component-model/src/design/wit.md
> +    blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;
Separately, I would maybe call this `blob-constructor` just so it doesn't seem like constructors are literally named after the resource :shrug:

2024-03-13 23:00 UTC, lann commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
I think I'd just like to balance "these are kind of like classes" with a little "but only kind of; beware".

2024-03-13 23:05 UTC, itowlson commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
Yeah but my questions about "can I pass them, where do I define them to do so" were not rhetorical - given what you're saying, I think we genuinely need to clarify that to developers.  Or am I missing something?  I am clearly missing something. _grin_

2024-03-13 23:07 UTC, dicej commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
I tend to think of resources as interfaces (or traits or protocols or abstract base classes or whatever term you're used to) rather than classes: there can (and usually will) be multiple implementations, and those implementations are not interchangeable.  You can certainly pass handles to a given implementation within and across components, though.

2024-03-13 23:20 UTC, lann commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
Yes you can pass them around. in order to work with (or even receive) a handle to a particular resource a component has to import that exact resource type, either directly from the component instance that defined it or indirectly via aliases/re-exports.

I think it ends up being fairly intuitive most of the time though with the way interfaces are reused in wit it could be confusing that two exports of the same interface produce incompatible resource handles.

2024-03-13 23:34 UTC, lann commented on component-model/src/design/wit.md
> +languages and can have constructors and methods.
Yes by default all imports will end up with the same instance if you aren't explicitly doing something "weird".

2024-03-15 17:25 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +}
@lann, the WIT explainer has the constructor also taking in a reference to self:
`%[constructor]blob: func(self: borrow<blob>, bytes: list<u8>) -> blob;`. Is that an error?

2024-03-15 17:37 UTC, lann commented on component-model/src/design/wit.md
> +}
Yeah that's an error. https://github.com/WebAssembly/component-model/pull/322

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +The WIT (Wasm Interface Type) language is used to define Component Model interfaces and worlds. WIT isn't a general-purpose coding language and doesn't define behaviour; it defines only _contracts_ b
> The WIT (Wasm Interface Type) language is used to define Component Model interfaces and worlds.

I know this was already here (so feel free to ignore), but do we expect people to know what "worlds" are? I wonder if this can be phrased in a way that doesn't yet use the specific vernacular of the component model but still indicates the overall shape of what we're talking about.

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +records, they describe things that can't or shouldn't be copied by value.
This feels a bit jargony. I'm not quite sure what the right wording would be, but perhaps something like:

> Resources are handles to some entity that lives outside of the component. Unlike other WIT types which are simply plain data, resources only expose behavior through methods.

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +handle. Resources are similar to Rust `trait`s or C# and TypeScript `interface`s
I don't think it's quite right to say resources are like Rust's traits. They are exactly like trait objects (e.g., `Box<dyn MyTrait>`). Where are traits are description of some interface, trait objects are an opaque reference to an implementation of that interface - the same as resources.

In TypeScript and C#, I think resources are also not quite interfaces. They are objects which implement an interface.

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +- _methods_: functions that implicitly take a `self` (similar to `this`)
> (similar to `this`)

I think we can just say:

> (often called `this` in many languages)

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +    merge: static func(lhs: borrow<blob>, rhs: borrow<blob>) -> blob;
I would personally not mention `borrow` here. It risks confusing the reader. Can we just have this method take ownership of the `lhs` and `rhs`?

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +but are meant to be lexically nested in the scope of the resource type
```suggestion
but are meant to be nested in the scope of the resource type
```

I'm not sure `lexically` adds too much and can be jargony and confusing.

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +blob-read: func(self: borrow<blob>, n: u32) -> list<u8>;
Has `borrow<T>` been explained at all?

2024-03-16 07:39 UTC, rylev commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed `self` parameter whereas constructors
I think we need to be more verbose in our explanation of this. While this explanation probably makes a lot of sense to Rust and C programmers, it probably doesn't make any sense to programmers of GCed languages.

2024-03-18 17:03 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +records, they describe things that can't or shouldn't be copied by value.
But then what is a `handle`? I am trying to avoid too many concepts, but i get that we can use the word handle without refering to a `handle` in the component model sense. I did originally have a section on `handle`s but we decided to remove a section in this thread https://github.com/bytecodealliance/component-docs/pull/103#discussion_r1523937953 to simplify.

2024-03-18 17:07 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +handle. Resources are similar to Rust `trait`s or C# and TypeScript `interface`s
There is a discussion on what analogy to draw in this thread: https://github.com/bytecodealliance/component-docs/pull/103#discussion_r1523973325. I will try to rewrite this with this feedback in mind, but i am coming to the conclustion that no analogy can be drawn

2024-03-18 17:22 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +handle. Resources are similar to Rust `trait`s or C# and TypeScript `interface`s
I removed any analogy and worked up to emphasizing they are "objects that implement" interfaces.

2024-03-18 17:38 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +blob-read: func(self: borrow<blob>, n: u32) -> list<u8>;
We had a note about it, but i moved it out of the note into a paragraph below this text. Let me know what you think

2024-03-18 17:40 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +Methods always desugar to a borrowed `self` parameter whereas constructors
Can we leave this to a future iteration? There is a lot of feedback i am juggling here and i fear that digging into this deeper will create another round of feedback that may be better explored in it's own PR. I would like to get this in before KubeCon WasmDay.

2024-03-18 17:42 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +The WIT (Wasm Interface Type) language is used to define Component Model interfaces and worlds. WIT isn't a general-purpose coding language and doesn't define behaviour; it defines only _contracts_ b
In the least, this is a good call out to link to the docs on `worlds`. I'd rather link to more documentation on terms than avoid terms.

2024-03-18 17:45 UTC, kate-goldenring commented on component-model/src/design/wit.md
> +two components. When the owner of an owned handle drops that handle, the
I'd love to punt this to a future iteration. Happy to capture this feedback into an issue we can track on explaining the terms more generically

2024-03-18 22:28 UTC, kate-goldenring commented
@rylev @itowlson do you mind giving this another look? There is a lot of great feedback here. I'd love to get something in for starters and iterate from there.

2024-03-18 22:31 UTC, itowlson approved these changes
LGTM - I think this is a great distillation of the essentials, and as you say, we can iterate on the details over time.  Thanks for your patience balancing the different viewpoints here.

2024-03-19 15:36 UTC, merged