fix: bring documentation and tutorials up to date with latest tooling
bytecodealliance/component-docs pull request #106
Opened 2024-03-15 21:35 UTC by kate-goldenring

A lot of the language guides were out of date. This updates:
- The example host tutorial to use latest wasmtime
- removes unnecessary component model flag for `wasmtime`
- removes two files that were stranded a while ago (under `/implementations` ) when they were moved to `runtimes`
- calls out `componentize-py` and `wasmtime-py` compatibility to avoid this issue https://github.com/bytecodealliance/component-docs/issues/84

I ran through everything and got it working. Ideally we can get this in and iterate if there is a lot of syntactical feedback

2024-03-17 20:39 UTC, itowlson requested changes
This is great - it is so good to finally see the tooling starting to smooth out its rough edges.  And I love how you've made the flow through the different tutorials more consistent.

My comments are mostly nits except for the one on the printout of the generated Python bindings.  I bounced off that pretty hard I'm afraid.  But the rest is great.

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/javascript.md
> +A component can be created from a JS module using `jco componentize`. First, install `jco`:
This paragraph removes the instruction to install `componentize-js`, but that instruction is still shown in the `npm` commands just below.  Which is correct?

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/python.md
> +### Building a Component that exports an interface
Nit: capitalisation in this title is a bit random (as, admittedly, it was in the previous iteration).

(Longer term we should pick either Sentence case or Title Case and align all our headings around it.  But that's definitely out of scope for this PR!)

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/python.md
> +The [sample `add.wit` file](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/example-host/add.wit) exports a function. However, to use your component from another
```suggestion
The [sample `add.wit` file](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/example-host/add.wit) exports a function. However, to use your component from another component, it must export an interface. (Most WITs you'll see in the wild do use interfaces; we've been simplifying by exporting a function.)  Let's expand our example world to export an interface rather than directly export the function.
```

Or something like that.  Just trying to address the "wait why has the book been showing us the _exact thing_ it now says we'll rarely find" reaction.

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/python.md
> +If you peak at the bindings, you'll notice that we now implement a class for the `add` interface rather than for the `example` world. This is a consistent pattern. As you export more interfaces from
```suggestion
If you peek at the bindings, you'll notice that we now implement a class for the `add` interface rather than for the `example` world. This is a consistent pattern. As you export more interfaces from your world, you implement more classes. Our add example gets the slight update of:
```

pet peeve alert

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/python.md
> +class Add(example.Example):
The explanatory paragraph said "we now implement a class for the `add` interface rarher than the `example` world, but this still inherits from `example.Example`.  It would be good to clarify what makes this implement that specific interface (of all the ones in the `example` world).  Is it the class name?

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/python.md
> +$ echo "7a64aa30ac7d91b03448001dcdc23760a80c58ecaf220bc70998d49b88820440  add.wasm" | sha256sum --check
This feels like it could easy slip out of sync if we ever rebuild `add.wasm`.

2024-03-17 20:39 UTC, itowlson commented on component-model/src/language-support/python.md
> +        ret = self.lift_callee0(caller, _clamp(x, -2147483648, 2147483647), _clamp(y, -2147483648, 2147483647))
Yikes!  Does the user need to understand all this stuff?!  Could we elide it, or move it to an "internals" section?  If not, can we clarify to readers what they should be looking at?

2024-03-18 16:07 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +### Building a Component that exports an interface
Yeah maybe we add a style guide

2024-03-18 16:07 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +The [sample `add.wit` file](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/example-host/add.wit) exports a function. However, to use your component from another
Good point. I also have an issue up to switch to using an interface in a different iteration

2024-03-18 16:09 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +If you peak at the bindings, you'll notice that we now implement a class for the `add` interface rather than for the `example` world. This is a consistent pattern. As you export more interfaces from
🙈

2024-03-18 16:10 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +$ echo "7a64aa30ac7d91b03448001dcdc23760a80c58ecaf220bc70998d49b88820440  add.wasm" | sha256sum --check
Should we remove the checksum since it is a module rather than an executable binary? Or we can add a `add-checksum` file next to it to make it more obvious

2024-03-18 16:12 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +        ret = self.lift_callee0(caller, _clamp(x, -2147483648, 2147483647), _clamp(y, -2147483648, 2147483647))
This is all generated code that i wanted to show them in the docs. Normally in the docs, we have not shown the bindings that are generated -- so I will remove this section

2024-03-18 19:51 UTC, itowlson commented on component-model/src/language-support/python.md
> +$ echo "7a64aa30ac7d91b03448001dcdc23760a80c58ecaf220bc70998d49b88820440  add.wasm" | sha256sum --check
I'd probably remove the checksum because I have a childlike faith in the Wasm sandbox.  Having a checksum file available for people who want it is probably a decent plan, as long as we can automate maintenance.  Is the .wasm file built in CI or do authors build locally and check it in?

2024-03-18 19:54 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +$ echo "7a64aa30ac7d91b03448001dcdc23760a80c58ecaf220bc70998d49b88820440  add.wasm" | sha256sum --check
> authors build locally and check it in
this one. Can can have CI for it in the future.

2024-03-18 19:57 UTC, kate-goldenring commented on component-model/src/language-support/python.md
> +$ echo "7a64aa30ac7d91b03448001dcdc23760a80c58ecaf220bc70998d49b88820440  add.wasm" | sha256sum --check
I removed the checksum

2024-03-18 22:25 UTC, merged