feat: improve JS lang docs
bytecodealliance/component-docs pull request #146
Opened 2024-08-07 17:16 UTC by vados-cosmonic

2024-08-12 16:35 UTC, kate-goldenring reviewed
@vados-cosmonic, do you mind providing some context around this PR? It isn't linked to an issue nor has a description. Are you aiming to fill a specific gap in the JS documentation by adding a new example and explaining WIT to JS type mappings?

2024-08-12 16:35 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +```
This is a redundant step to the next "Building a component with jco" step. Can you remove the jco install from that step or remove this added section.

2024-08-12 16:35 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +`jco` can be perform this conversion (referred to as "transpilation"):
```suggestion
`jco` can perform this conversion (referred to as "transpilation"):
```

2024-08-12 16:35 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +You should see the following output:n
```suggestion
You should see the following output:
```

2024-08-12 16:35 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +Reactor components are WebAssembly components that are long runnign and meant to be called repeatedly over a long period of time. They're analogous to libraries of functionality rather than an execut
```suggestion
Reactor components are WebAssembly components that are long running and meant to be called repeatedly over a long period of time. They're analogous to libraries of functionality rather than an executable (a "command" component).
```

2024-08-13 07:00 UTC, vados-cosmonic commented
Hi @kate-goldenring sorry for the delay in responding here -- While working on `jco` I was looking at the docs and realized that the javascript section wasn't quite as filled out as the Rust section. I originally started trying to *at least* add similar sections the JS version, but the effort kind of grew :sweat_smile: 

Ideally I'd like to at least have some more code sections/examples for the JS stuff that matches Rust/some of the other developed toolchains -- apologies, I should have made an issue first to capture what I wanted to add.

2024-08-13 07:29 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +```
Ah thanks, yeah I want to opt for removing the `jco` install from the other step, what do you think? I like the idea of "how to install" as a separate section since it seems common to expect/can can vary.

2024-08-13 11:48 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +```
I've modified the PR bit with how I was thinking it should look -- would definitely appreciate some feedback/edits.

2024-08-19 13:06 UTC, vados-cosmonic commented
Hey @kate-goldenring also another thing here -- in an bid to lower the scope of this PR, what do you think about moving the code examples to `jco` directly and *linking* to them from here? Just thinking back on this, the PR isn't done yet but it's probably unreasonable to include the code here when it could be kept a bit closer to `jco` (and possibly kept under test)

2024-09-11 17:13 UTC, kate-goldenring commented
@vados-cosmonic, I think the scope of this PR is reasonable. To me, it adds a second example host, namely a JCO one in addition to our current rust one. Once this is in a state you deem ready to review and after merging, we can move both host CLI examples into one folder. I would love to get these updates to `javascript.md` in.

2024-09-24 18:20 UTC, kate-goldenring commented
@vados-cosmonic just want to check in here. Do you want to change the scope of this PR or prioritize getting in a certain section of it?

2024-09-25 10:35 UTC, vados-cosmonic commented
Hey @kate-goldenring sorry for the delay here -- I'm going to try and get this done *this week*! I'm fine keeping the scope the same, and if the code gets overbearing we can always move it out to `jco` (we could use an `examples` folder at the top level in there anyway)

2024-09-30 16:26 UTC, vados-cosmonic commented
Hey @kate-goldenring sorry for the delay here, but the branch is finally looking reasonable!

There's a lot of new code (all those new lines are mostly from `package-lock.json`s!), but this should now be a quite complete introduction to the early parts of 

Full disclosure, I had some sections that I removed -- particularly the way types are translated, how to run with `wasi:cli` and how to use resources -- the PR is already long enough as is! If possible I'd like to contribute those sections in a follow up.

2024-09-30 16:31 UTC, vados-cosmonic commented
Oh also ping @guybedford -- any comments you have would be greatly appreciated :)

I'm also of half a mind to link to these examples (or copy them outright?) to `jco` as well, that repo would benefit from an `examples` folder I think!

2024-10-01 17:41 UTC, guybedford reviewed
This looks great, thanks for working on it!

2024-10-01 17:41 UTC, guybedford commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
> +This folder contains a Javascript project can build into a WebAssembly component binary.
```suggestion
This folder contains a Javascript project that can be built into a WebAssembly component binary.
```

2024-10-01 17:41 UTC, guybedford commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
> +```
Did you mean to fill this in?

2024-10-01 17:41 UTC, guybedford commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
> +After running component composition, there will be a component with all it's imports satisfied, called `string-reverse-upper.composed.wasm`.
```suggestion
After running component composition, there will be a component with all its imports satisfied, called `string-reverse-upper.composed.wasm`. 
```

2024-10-01 17:41 UTC, guybedford commented on component-model/examples/tutorial/jco/string-reverse/README.md
> +This folder contains a simple Javascript project can build into a WebAssembly binary.
```suggestion
This folder contains a simple Javascript project that can be built into a WebAssembly binary.
```

2024-10-01 19:40 UTC, kate-goldenring requested changes
Thank you for filling in all this content! I had a lot of thoughts about structure that I will summarize here. The incongruencies show how we could do a better job explaining and expanding the structure of our examples directory. I am proposing below what works best with the current structure but acknowledge that we may want to follow up with a better structure.

1. The `examples/tutorial` folder is for all components and host runtimes that have to do with implementing or executing the `calculator` world. The `cli-calc.js`  executes `evalExpression` from that world. Can you add it back in?
2. You provide a new host for the example world. Can you move it (`run-transpiled.js`) to `examples/example-host` and update your example to use that WIT as well (the `example` world) rather than renaming it to `adder` world. For now, can you remove your example implementation of the add component? We don't provide any example implementations for other languages. In the future, we may want to create a `example/example-world` folder with example hosts and impls below that.
3. I'd recommend adding the string-reverse and string-reverse-upper examples to JCO where they can be better maintained. If that isn't an option, in the least, they should be moved to the top level of the `examples` directory.

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/examples/tutorial/jco/add/README.md
The other language guides do not provide an example for `add` rather explain the implementation in the document. Whether or not that is a pattern worth maintaining, this example does not fit under the tutorial (`examples/tutorial`) which defines different WIT worlds. Rather it would be an alternative implementation path for `add.wasm` in `examples/example-host`. Looking at the wits of each directory may help with that.

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
I am hesitant to add more examples to the repo itself. If we do, this should live at the top level under `examples` not under the tutorial

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +Installing [`jco`][jco] (and it's required peer dependency [`componentize-js`][componentize-js]) can be done via NodeJS project tooling:
```suggestion
Installing [`jco`][jco] (and its required peer dependency [`componentize-js`][componentize-js]) can be done via NodeJS project tooling:
```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> `jco` and `componentize-js` in a project-local manner with `npm install -D`
I am not sure this syntax works for mdbook. I'd recommend removing:

```suggestion
> `jco` and `componentize-js` in a project-local manner with `npm install -D`
```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> `jco` and `componentize-js` in a project-local manner with `npm install -D`
```suggestion
> [!NOTE]
> `jco` and `componentize-js` can be installed in a project-local manner with `npm install -D`
```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +[ComponentizeJS][componentize-js] only provides compilation tools (JS -> WASM transpilation) used by `jco`, so installing both packages is required.
```suggestion
[ComponentizeJS][componentize-js] provides tooling used by `jco` to transpile JS to Wasm, so installing both packages is required.
```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +The [`examples/tutorial/jco/add` example](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/add) will use the [`adder` world](https://github.com/bytec
Please use a WIT already used in the docs. Either 
1. the wit used by all language guides with the `example` world https://github.com/bytecodealliance/component-docs/blob/main/component-model/examples/example-host/add.wit
2. the [`adder` world](https://github.com/bytecodealliance/component-docs/blob/d810c3599d391e1a911cbbfb6889dac1d2754625/component-model/examples/tutorial/wit/adder/world.wit) from the tutorial. we will probably want to update all examples in the language guide to use this WIT instead given that it uses an interface.

I'd like to avoid bringing in a third one that looks similar to the other two. it already is a little confusing. Doing 1 means you can use the Rust `example-host` to execute it. If you do 2, we can then use this as the new host as we move towards updating to the adder world in the examples

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> without having `jco` and `componentize-js` installed globally.
I would clarify here that you can run it as a native binary instead of wasm

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +cd component-model/examples/example-host
Have you tested this? Does it work given you've changed the name of the world?

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> [!WARN]
does not appear to be a valid marker when i do a `mdbook serve`
```suggestion
```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +
```suggestion
A quick reminder on the power and new capabilities afforded by WebAssembly -- we've written, loaded, instantiated and executed Javascript from Rust with a strict interface, without the need for FFI, subprocesses or a network call.

```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> You can also use `npm run transpile` which outputs to `dist/transpiled`
what is the difference here? Why would someone choose to do this?

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +(Javascript) natively.
```suggestion
This is directly comparable to the Rust host code mentioned in the previous section. The Javascript code *also* runs the WebAssembly binary (which could have been written in any language) from the host language
(Javascript) natively.
```

2024-10-01 19:40 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> language with any language that supports using a WebAssembly runtime (ex. `wasmtime`)
Seems like a verb is missing here? it can be executed?

2024-10-02 06:51 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
> +```
Absolutely did -- I forgot!

These examples will probably move out to `jco`, but I will remember to fix this before I do. 

- [ ] Add missing output in `string-reverse-upper` README
- [ ] Update other READMEs to quality of `string-reverse-upper`

2024-10-02 06:57 UTC, vados-cosmonic commented
Hey @kate-goldenring thank you for taking the time and the detailed review! 

Just to hit the points in your overview (which was also helpful!) -- I agree on the structure, and thanks for letting me know the intended organization, that sounds fine to me. 

Changing to a new structure should probably follow a more proper issue + discussion + PR process. I was hoping this change was *small*, and clearly... it's no longer that! :sweat_smile: 

>    The examples/tutorial folder is for all components and host runtimes that have to do with implementing or executing the calculator world. The cli-calc.js executes evalExpression from that world. Can you add it back in?

Absolutely, will add this back in!

>    You provide a new host for the example world. Can you move it (run-transpiled.js) to examples/example-host and update your example to use that WIT as well (the example world) rather than renaming it to adder world. 

Will do this as well! The host in `example-host` is Rust-based, but the host in `run-transpiled` is JS based, does it make sense to split those up? `examples/hosts/js` & `examples/hosts/rust` ?

> For now, can you remove your example implementation of the add component? We don't provide any example implementations for other languages. In the future, we may want to create a example/example-world folder with example hosts and impls below that.
>
>    I'd recommend adding the string-reverse and string-reverse-upper examples to JCO where they can be better maintained. If that isn't an option, in the least, they should be moved to the top level of the examples directory.

Yup, will remove the `add` component -- I'll move that to `jco` probably along with most of the other examples, it's probably bit much to have the code essentially reproduced in the docs *and* committed to the documentation project. These examples make a lot of sense as part of `jco`. 

Again, thanks for the reviews and general feedback as well -- will get to making these changes soon!

2024-10-02 06:58 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +((TODO))
Ah this is a great point, I actually meant to *remove* this section all together since it wasn't written yet. Rather than do that, I'll make this change!

2024-10-02 06:59 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +((TODO))
Weird, I think this comment was somehow leftover/not shown from the last round, this *was* removed (I removed the sections since they weren't ready) -- so will resolve this

2024-10-02 07:01 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/cli-calc.js
Ah thanks for pointing this out -- this was an accidental delete, I thought I added this for some reason!

- [ ] re-add `cli-calc.js`

2024-10-02 07:02 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/add/wit/component.wit
Absolutely, will rework the names here and use the same file. 

- [ ] Remove duplication of `example-host/add.wit`

2024-10-02 07:06 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/add/README.md
This example should probably be moved out to `jco` in general, but I wanted to point out that I wanted this be the JS implementation equivalent of [`adder`](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/adder)... 

That said I think making the tutorial work for multiple languages is indeed a different, wider conversation -- will remove this bit!

2024-10-02 07:07 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
Yup -- I think what I was looking at here was anywhere that seemed to be "js" related -- `examples/tutorial/jco` just seemed like the only place that might contain javascript-specific examples! 

That said, will definitely move these out

2024-10-02 07:09 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> `jco` and `componentize-js` in a project-local manner with `npm install -D`
It can, with the help of [`mdbook-alerts`](https://crates.io/crates/mdbook-alerts)

I think it'd be great to have the nice alert rendering in both mdbook and github -- if you're OK with it, I'll add `mdbook-alerts` to the rendering.

2024-10-02 07:10 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +The [`examples/tutorial/jco/add` example](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/add) will use the [`adder` world](https://github.com/bytec
Will update -- yes we can absolutely use the `add.wit` -- I would have gone with (1), other than the fact that the `add` example should be moved in the first place.

2024-10-02 07:13 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> without having `jco` and `componentize-js` installed globally.
I think it might be a little weird to say that just because of how NodeJS works but I will try and change this -- mabye "a regular NodeJS project" makes more sense?

2024-10-02 07:14 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> You can also use `npm run transpile` which outputs to `dist/transpiled`
So this makes sense in the conte4xt of the lines above -- transpilation is a way to use the wasm modules *inside* a regular JS project or in the browser

2024-10-02 07:15 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> language with any language that supports using a WebAssembly runtime (ex. `wasmtime`)
Ah that "with any language" should be removed!

2024-10-02 07:28 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +cd component-model/examples/example-host
Yup I tested this and it works but it *could* fail if people didn't follow the steps above. 

Committing `add.wasm` would make it work 100% of the time, but since `add` is going to move out of this repo I'll probably revert the changes here and use the placeholder `../path/to/add.wasm`, as it was before

2024-10-02 07:30 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> You can also use `npm run transpile` which outputs to `dist/transpiled`
Maybe I'm misunderstanding the question here -- `npm run` is quite baked in for NodeJS users -- maybe it's unclear that the note here is encouraging `npm run <task>` *versus* typing out the `jco` command explicitly every time

2024-10-02 16:40 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
> +```
Ah so these changes have been made, but in the jco PR!

2024-10-03 15:57 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/add/wit/component.wit
This project was removed!

2024-10-03 15:57 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/add/README.md
Moved the project!

2024-10-03 15:58 UTC, vados-cosmonic commented on component-model/examples/tutorial/jco/string-reverse-upper/README.md
This has been removed now

2024-10-23 19:56 UTC, kate-goldenring requested changes
@vados-cosmonic can you give this another iteration? JCO examples are still referenced that do not exist in upstream jco and `cli-calc.js` should be used as the jco host instead of creating a new one.

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/book.toml
> +additional-css = ["theme/head.hbs"]
nit: @vados-cosmonic can you undo this change? Looks like a whitespace addition

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +The first step in building a WebAssembly component is creating or downloading the interface that defines what your component can do. This usually means creating or downloading the [WebAssembly Interf
I am still not seeing `[WebAssembly Interface Types ("WIT")][wit]` rendered appropriately even with the latest plugins and mdbook. Can you confirm this is rendering appropriately for you @vados-cosmonic? Maybe share a screenshot?

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +world adder {
Per previous discussions, can you revert these changes and use the existing add.wit.

```suggestion
package example:component;

world example {
```

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +The [`examples/tutorial/jco/add` example](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/add) will use the [`adder` world](https://github.com/bytec
This looks like it needs updating to use the existing add.wit which have an `example` world

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +- Loads the WebAssembly binary at the provided path (in the command above, `../tutorial/jco/add/add.wasm`)
please update path
```suggestion
- Loads the WebAssembly binary at the provided path (in the command above, `../path/to/add.wasm`)
```

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +This example renames it and imports it as an ECMAScript module for ease of running locally with [NodeJS][nodejs] (you can find this code in [`run-transpiled.js`](https://github.com/bytecodealliance/c
This no longer exists. Should it be referencing `cli-calc.js` instead?

2024-10-23 19:56 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +[examples-string-reverse]: https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/string-reverse
These no longer exist. Can they be moved upstream into jco or can we reference existing jco examples?

2024-10-23 20:02 UTC, vados-cosmonic commented on component-model/book.toml
> +additional-css = ["theme/head.hbs"]
Hey kate, sorry are you missing the `[preprocessor.alerts]` line at the bottom of this file? There's a new line in here

2024-10-23 20:05 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +The first step in building a WebAssembly component is creating or downloading the interface that defines what your component can do. This usually means creating or downloading the [WebAssembly Interf
Ah it wasn't rendering properly because I mistakenly named the `[wit]` reference `[wit-spec]` -- fixed!

2024-10-23 20:12 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +The [`examples/tutorial/jco/add` example](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/add) will use the [`adder` world](https://github.com/bytec
Ah yes -- the way the component is written in the other example (i.e. not the one I wrote), is quite different, left this out but it should be updated.

2024-10-23 20:17 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +The [`examples/tutorial/jco/add` example](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/add) will use the [`adder` world](https://github.com/bytec
Just updated this -- required some changes to the links and also the instructions for compiling the code.

2024-10-23 20:53 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> You can also use `npm run transpile` which outputs to `dist/transpiled`
Hey @kate-goldenring going to resolve this, please let me know if this is still confusing!

2024-10-23 20:54 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +[examples-string-reverse]: https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/tutorial/jco/string-reverse
Thanks for catching this -- yes, this absolutely should be pointing to `jco`, those have been merged upstream now

2024-10-23 21:01 UTC, vados-cosmonic commented
Hey @kate-goldenring thanks for taking another look at this -- with the exception of one of the things you pointed out, I've been able to address the other issues! The alerts render just fine as well though `WARN` should have been `WARNING`!

2024-10-23 21:18 UTC, kate-goldenring requested changes
@vados-cosmonic i am still confused by why you are using the tutorial wit instead of the example wit

2024-10-23 21:18 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
Can you explain why you are using this interface? Other examples use [add.wit](https://github.com/bytecodealliance/component-docs/blob/main/component-model/examples/example-host/add.wit) which is the world expected by the host-example you execute later

2024-10-23 21:27 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
Ah this is because there is no `add` example written in JS in this repo -- I should not be referencing the tutorial example but should be referencing `jco` instead here, like everywhere else in the guide!

It probably doesn't make sense to reference the tutorial WIT when we don't have *actual code* in here that points to it, like the rust example (since that was moved to `jco`). 

What I *should* have done here was pointed to the example in `jco` in the first place.

2024-10-23 21:29 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
Ideally, I'd like to have a repo/working code available for each example -- I think right now the other examples kind of expect you to write all the code?

2024-10-23 21:38 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
Maybe I've misunderstood something about the structure of the component-docs -- the language-specific sections come *before* the tutorial, and none of the other languages actually effectively use the rust host to run the components. 

Is the idea that the language specific guides are *part* of the future tutorial? Or that they should stand alone as references? I was thinking it was the latter!

2024-10-23 21:46 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
@vados-cosmonic could you look at one of the other language guides in the docs for reference? The idea is to provide guidance on implementing this [world](https://github.com/bytecodealliance/component-docs/blob/main/component-model/examples/example-host/add.wit). You don't need to reference a complete solution. Then, you can point them to the [example host](https://github.com/bytecodealliance/component-docs/tree/main/component-model/examples/example-host) to execute it (as you already do).

The tutorial is separate of the language guides. I would not reference any of those worlds in the language guide

2024-10-23 23:05 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
Wow, I just  completely misunderstood the intent here -- I will make a language guide identical to the existing ones, The stuff in here was more to go with the examples, and that's not what the others were doing at all. 

Apologies, will rework this :bow:

2024-10-23 23:09 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
I don't think you need to do too much reworking. it is great if this goes above and beyond the other guides but the baseline (add example) should be the same. You can still walk through the jco examples here since they are hosted in jco.

2024-10-23 23:15 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +package docs:adder@0.1.0;
Ah OK, so what I will make sure to do is near carbon copy the format of the other guides, and add any extra information to the bottom as new sections. 

That should make it easy to differentiate (and review) stuff matching the existing format and new more JS specific content!

2024-10-28 15:02 UTC, vados-cosmonic commented
Hey @kate-goldenring if you wouldn't mind taking another look -- I've mirrored the other guides and kept in the more advanced sections, with links back to `jco` for the full code listing.

2024-10-28 16:29 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +The [`example` world][wit-example-world] showcases a WIT world that adds two numbers together:
```suggestion
The [`example` world][wit-example-world] exports a single `add` function that sums two numbers:
```

2024-10-28 16:55 UTC, kate-goldenring requested changes
Just a few final suggestions

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +
I think this is a little confusing because the package declaration is not a part of the world. I think the leading sentence recommended in https://github.com/bytecodealliance/component-docs/pull/146/files#r1819378981 is sufficient.
```suggestion
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +> To learn more about the WIT syntax, check out the full [WIT specification][wit]
We have a WIT explainer in the component book that aims to be more easily consumed than the upstream one. Please point them there instead of having them leave the book: https://component-model.bytecodealliance.org/design/wit.html

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +## Writing the JS to build a WebAssembly component
nit suggestion 
```suggestion
## Implementing a JS WebAssembly component
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +To implement the [`example` world WIT interface][wit-example-world], we must write a [JavaScript module][mdn-js-module]
```suggestion
To implement the [`example` world][wit-example-world], we must write a [JavaScript module][mdn-js-module]
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +Our component is *so simple* (reminiscent of [Core WebAssembly][wasm-core], which deals primarily in numeric values) that we're actually *not using* any of the [WebAssembly System Interface][wasi] --
What happens if you do not disable?

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +## Running a Component from JavaScript Applications (including the Browser)
nit: use consistent capitalization for headers

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +This is directly comparable to the Rust host code mentioned in the previous section. Here, we are able to
this PR could be followed up by adding this host to the examples directory

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +Reactor components are WebAssembly components that are long running and meant to be called repeatedly over time. They're analogous to libraries of functionality rather than an executable (a "command"
> Reactor components are WebAssembly components that are long running and meant to be called repeatedly over time.

To me, this makes it seem like reactor components are daemons that react to events. I think of them as anything that does not export the `run` function. What is your intent in emphasizing what a reactor component is? How about saying the following and then just calling it a component from then on
```suggestion
Lets look at how to implement a library of functionality in a component using the JavaScript tooling. Components that act as libraries can be thought of as "reactor" or "library" components. This contrasts with a "command" component, which has a specific `run` export that allows it to be executed directly by wasmtime (or other `wasm:cli` hosts). 
```
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +Reactor components (and components in general) expose their interfaces via [WebAssembly Interface Types][docs-wit], hand-in-hand with the [Component Model][docs-component-model] which enables compone
```suggestion
Components expose their interfaces via [WebAssembly Interface Types][docs-wit], hand-in-hand with the [Component Model][docs-component-model] which enables components to use higher level types interchangably.
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +Up until now, we have focused on building reactor components.
Until now? Don't we continue to?
```suggestion
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +- We've defined a namespace called `examples`
```suggestion
- We've defined a namespace called `example`
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +- We've defined a package called `rev` inside the `examples` namespace
```suggestion
- We've defined a package called `string-reverse` inside the `example` namespace
```

2024-10-28 16:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +- This WIT file corresponds to version `0.1.0` of `example:rev` package
Please review this section. Some of it does not match the wit

2024-10-29 03:14 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +
OK, will remove this section!

2024-10-29 03:16 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +## Writing the JS to build a WebAssembly component
Thanks!

2024-10-29 03:19 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +Our component is *so simple* (reminiscent of [Core WebAssembly][wasm-core], which deals primarily in numeric values) that we're actually *not using* any of the [WebAssembly System Interface][wasi] --
Nothing! Do you want me to remove that note? The purpose of this section was to point towards WASI and make a distinction between core web assembly and what's offered by CM + WASI

2024-10-29 03:23 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +This is directly comparable to the Rust host code mentioned in the previous section. Here, we are able to
Ah great idea, I'll keep that in mind! As the JS host is sort of the secondary implementation we test things in, that would be a good thing to have in here as a cross-check/other example.

2024-10-29 03:31 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +Reactor components are WebAssembly components that are long running and meant to be called repeatedly over time. They're analogous to libraries of functionality rather than an executable (a "command"
> To me, this makes it seem like reactor components are daemons that react to events.

Unfortunately, this *is* a valid lens to look at reactor components, I think. They kind of act in both this way, and also as library of functionality to other components (not to be confused with shared libraries like `somelib.so`), depending on how they're used. 

Yeah, the problem here was that I really wanted to link out to more involved descriptions of the difference, but command components are actually *not* just everything that does not export `wasi:cli/run` (I wish they were) -- and there used to be a doc on the difference but it's gone now (I think it got stale).

The actual distinction of start vs command component is [whether there is a `_start` export](https://github.com/bytecodealliance/wasm-component-ld/blob/e00ddf3d8d9f43d6d58d6661c9a48c1ed0733dc3/src/lib.rs#L587). It's a subtle difference but `wasmtime` and other hosts can *interact* with `wasi:cli/run` because it's a pre-established interface/support is built in, but IIRC that's not the main difference!

@guybedford please correct me if I'm wrong here!

Happy to either make this change or remove the section as a whole (arguably it may not be needed) though

2024-10-29 03:33 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +> To learn more about the WIT syntax, check out the full [WIT specification][wit]
Done!

2024-10-29 03:35 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +Up until now, we have focused on building reactor components.
Yep -- building a command component isn't in here, this was not meant to imply that anything would change. Will remove as it could be confusing

2024-10-29 03:40 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +- This WIT file corresponds to version `0.1.0` of `example:rev` package
Thanks, overlooked this after changing the WIT!

2024-10-29 17:55 UTC, kate-goldenring commented on component-model/src/language-support/javascript.md
> +## Running a Component from JavaScript Applications (including the Browser)
i dont think we have it defined, but keeping it consistent within a doc is a good baseline

2024-10-29 17:59 UTC, kate-goldenring approved these changes
@vados-cosmonic thank you for all the iterations on this! I know it has taken a lot of time but your knowledge in this space is clear. Would love your help maintaining this document and other documentation as time allows. 

For the reactor component thread, lets continue that discussion and we can always update the doc.

2024-10-29 18:00 UTC, merged

2024-10-30 06:47 UTC, vados-cosmonic commented
Hey @kate-goldenring thanks for the tireless reviews -- apologize for taking up so much of your time! With the edits, the documentation is so much better.

> Would love your help maintaining this document and other documentation as time allows.
I would love to help wherever I can, this time with the proper flow! If there are issues that are reasonable for someone in the Rust & JS ecosystems to tackle I'm certainly happy to help.

> For the reactor component thread, lets continue that discussion and we can always update the doc.
Yes, this time I'll make some issues to start!

2024-10-30 06:48 UTC, vados-cosmonic commented on component-model/src/language-support/javascript.md
> +## Running a Component from JavaScript Applications (including the Browser)
Ah thanks for pointing this out, I went back and made sure it was consistent in this doc