Add initial documentation for C tooling
bytecodealliance/component-docs pull request #66
Opened 2023-09-10 04:35 UTC by seanisom

Fixes #38 

Creating as a draft for now as I would like to see #44 merged first as that will change the structure of `language-support` - I will update the table of contents to match that once I can rebase from that.

2023-09-22 20:04 UTC, kate-goldenring requested changes
Thanks @seanisom! I was able to get this all working and running on the example host! There were a few parts where i deviated from the flow and a little bit more information we can add

2023-09-22 20:04 UTC, kate-goldenring commented on component-model/src/language-support/c.md
> +First, install the cli for [`wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen#cli-installation), [`wasm-tools`](https://github.com/bytecodealliance/wasm-tools), and the [`WASI SDK`](http
I think we need an explicit call out for how to set up `clang` since (at least for MacOS) the header files for `wasm32-wasi` aren't present by default. Following these steps resolved it for me: https://github.com/WebAssembly/wasi-sdk#use

2023-09-22 20:05 UTC, kate-goldenring commented on component-model/src/language-support/c.md
> +
Can we add a note here to test the component by running it against the `example-host`?

2023-12-07 23:42 UTC, sunfishcode commented
@seanisom It looks like #44 is merged now; are you able to continue working on this? In any case, would you like help finishing finishing this PR? There's good content here that would be great to have published; let me know if there's anything I can do to help!

2023-12-11 04:53 UTC, seanisom commented
Hey @sunfishcode @kate-goldenring , sorry for letting this go stale! Will rebase on top of the latest post #44 and incorporate the feedback.

Regarding host component support for C in wasmtime, I need to follow up on https://github.com/bytecodealliance/wasmtime/issues/6987 - Bailey mentioned Alex may have already started this work. If that is complete or a significant uplift I can address that in a follow-up PR.

2024-03-21 09:12 UTC, rylev commented
@seanisom @kate-goldenring what's the state of this PR - is this blocked on anything in particular?

2024-04-11 05:16 UTC, breckcs commented
If this PR is going to be merged, don't forget to update the links on the landing page in `introduction.md`.

Go wasn't included there and at first I thought support for Go didn't exist. See: https://github.com/bytecodealliance/component-docs/pull/128.

2024-08-17 19:16 UTC, rajsite commented
I think it would be great to start getting some docs in for C development that can grow over time. There really doesn't seem to be a good source generally (compared to other languages which have detailed docs elsewhere) and in the time this has been in review it's gotten outdated:
- target names have changed in wasi-sdk)
- wasi-sdk has a dedicated p2 target
- changes have been made to the wasi targets such that folks have expected workflows that don't seem well documented (it's expected users know to strip debug symbols that are always included now).

Those kind of updates would be easier to make in small PRs if the C docs became available.

2024-08-19 15:25 UTC, kate-goldenring commented
@rajsite would you be willing to take on updating the docs? You could also open a new PR with the content and @seanisom could potentially jump in to review it

2024-08-27 18:27 UTC, merged