Add Go language guide
bytecodealliance/component-docs pull request #77
Opened 2023-09-23 00:16 UTC by kate-goldenring

Add go language guide

2023-09-23 00:17 UTC, kate-goldenring commented
Currently debugging why the resultant `add.component.wasm` is not compatible with our `example-host`. I am getting:
```
Error: Failed to instantiate the example world

Caused by:
    0: import `wasi:io/streams` has the wrong type
    1: instance export `check-write` has the wrong type
    2: expected func found nothing
```

2023-09-26 22:45 UTC, kate-goldenring commented
updating wasmtime version did the trick so this is ready for review

2023-09-27 01:07 UTC, itowlson requested changes
Thanks for doing this!  The spine of it is great, but reading it I sometimes felt a bit adrift.  Key suggestions would be:

1. A bit more of a roadmap up front. We can't go directly from busting out some Go to having a component, so here are the waypoints we're going to hit.
2. A bit more what and why, around things like the `init`, `SetExample` stuff.

But the core story is great!  So good to have this in here.

2023-09-27 01:07 UTC, itowlson commented on component-model/examples/example-host/Cargo.toml
> +wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "aec4b25", features = ["component-model"] }
Do any of the other tutorials need updating to remain in line with the new build, or do they continue to work?

2023-09-27 01:07 UTC, itowlson commented on component-model/src/language-support/go.md
> +//go:generate wit-bindgen tiny-go ./add.wit -w example --out-dir=gen
This looks like the line we just ran.  What is its role here?

2023-09-27 01:07 UTC, itowlson commented on component-model/src/language-support/go.md
> +> echo "replace github.com/yourusername/yourproject => /Path/to/add" >> go.mod
What does `/Path/to/add` mean here?  Is it the WIT file?

2023-09-29 21:42 UTC, kate-goldenring commented on component-model/src/language-support/go.md
> +# Go Tooling
I think a full book rev makes sense. I think it is better than leaving at "latest dev" since that already implies Wasmtime 13 changes

2023-10-02 22:09 UTC, kate-goldenring commented on component-model/src/language-support/go.md
> +//go:generate wit-bindgen tiny-go ./add.wit -w example --out-dir=gen
This makes it so you can automatically regenerate the bindings on builds if the WIT changes but it probably over complicates. I'll remove

2023-11-28 00:17 UTC, Mossaka commented on component-model/src/language-support/go.md
> +    SetExample(a)
The reasoning behind using `init()` is to register **user implementation** as exported interfaces / functions.

2024-04-05 19:55 UTC, kate-goldenring commented
@itowlson do you mind giving this another review? I broke the guide up into two sections: 
1. a quickstart that just exports an add function
2. one that uses wit-bindgen to support more complex worlds
I also call out how a lot of the `wasm-tools` commands to componentize with be unnecessary once the `wasip2` target is added.

2024-04-07 19:34 UTC, itowlson approved these changes
Couple of things to sanity-check but looks good!

2024-04-07 19:34 UTC, itowlson commented on component-model/src/language-support/go.md
> +   []`wasm-tools`](https://github.com/bytecodealliance/wasm-tools)
Is the extra `]` before `wasm-tools` intentional?

2024-04-07 19:34 UTC, itowlson commented on component-model/src/language-support/go.md
> +The next section will walk through steps 1-2, producing a core Wasm module that targets WASI preview 1.
Should we line up the ordering here - this next section is actually step 2 not step 1 I think?

2024-04-07 19:34 UTC, itowlson commented on component-model/src/language-support/go.md
> +   []`wasm-tools`](https://github.com/bytecodealliance/wasm-tools)
Again just sanity-checking the extra `]`

2024-04-09 20:18 UTC, kate-goldenring commented on component-model/src/language-support/go.md
> +The next section will walk through steps 1-2, producing a core Wasm module that targets WASI preview 1.
I updated the guide to number the headings and added a section introducing the `example` world. What do you think? [2be771c](https://github.com/bytecodealliance/component-docs/pull/77/commits/2be771c1c92c0d827d97a5e59223e19d9453588b)

2024-04-09 20:24 UTC, itowlson approved these changes
This is great - thank you Kate!

2024-04-09 20:39 UTC, merged